### ISSUE TITLE
Dash (-) character on column names

### ISSUE THREAD

**Issue by alpertuna** [philipsoutham/py-mysql2pgsql#101]
Hi,
When a table column name has a dash character, it splits name and tries to use part before dash.
For example, a column is named `some-column`, and when you run it, it throws
> column "some" does not exist

mysql and postgresql both supports dashes for columns.

Btw, love the script, thanks.

**Comment by kworr** [comment]
Can't reproduce on current source, added a sample table to test schema at 5bb3955c13f2f6b1198dcaf76c61fce80f95d2db and everything works fine.
