### ISSUE TITLE
quoting of column name is missed

### ISSUE THREAD

**Issue by ruv** [philipsoutham/py-mysql2pgsql#98]
Quoting is missed in `ADD CONSTRAINT ... PRIMARY KEY( column_name )` statement.
So this statement fails in case of the column name is reserved word.
Example:

```
psql:data/dump.pg.sql:930210: ERROR:  syntax error at or near "user"
LINE 1: ..." ADD CONSTRAINT "userlink_pkey" PRIMARY KEY(user);

```

**Comment by kworr** [comment]
Everything works for me and on current version so I added test case in d0652069443338eb0a0ba97dc4aa021dd8526edb.
